version: 2
jobs:
  build:
    working_directory: ~/mnl-api
    docker:
      - image: circleci/python:3.8.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: v3.8.2-{{ .Branch }}-{{ checksum "django/Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv install django
      - save_cache:
          key: v3.8.2-{{ .Branch }}-{{ checksum "django/Pipfile.lock" }}
          paths:
            - '.venv'
            - '/usr/local/bin'
            - '/usr/local/lib/python3.8/site-packages'
      - run:
          command: |
            echo ${SECRET_KEY}
            pipenv run python django/manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
